import Head from 'next/head';
import Image from 'next/image';
import Featured from '../components/Featured';
import { Hero } from '../components/Hero';
import ProductsList from '../components/ProductsList';
import axios from 'axios';

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Featured />
        <ProductsList products={products} />
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const res = await axios.get(`http://localhost:3000/api/products`);

  return {
    props: {
      products: res.data,
    },
  };
};
